<div class="field linkedin_profile">
    <label class="label" for="linkedin_profile">
        <span><?= $block->escapeHtml(__('Linkedin profile')) ?></span>
    </label>
    <div class="control">
        <input type="text" name="linkedin_profile" id="linkedin_profile" value="<?= $block->getLinkedInProfile() ?>"
               title="<?= $block->escapeHtml(__('Linkedin profile')) ?>" class="input-text">
    </div>
</div>
