<div class="Weather-container">
    <form method="POST" action="<?=  $block->getPostUrl() ?>" id="weather-form">
        <div class="wrapper">
            <div class="container">
                <div class="title">
                    <h1>Weather in your city</h1>
                </div>
    
                <div class="input-container">
                    <label for="city-input">
                        City *
                    </label>
                    <input type="text" id="city" name="city" placeholder="Enter city of your choice">
    
                    <button type="submit" class="search-btn">
                        Submit
                    </button>
                </div>
            </div>
    
            <div class="result-container">
                <ul>
                    <li><span>City: </span> <span class="city-result"><?= $block->getCity() ?></span></li>
                    <li><span>Country: </span> <span class="city-result"><?= $block->getCountry() ?></span></li>
                    <li><span>Description: </span> <span class="city-result">clear sky</span></li>
                    <li><span>Temperature (°C): </span> <span class="city-result"><?= $block->getTemperature() ?></span></li>
                    <li><span>Feels Like (°C): </span> <span class="city-result"><?= $block->getFeelsLike() ?></span></li>
                    <li><span>Pressure (hPa): </span> <span class="city-result"><?= $block->getPressure() ?></span></li>
                    <li><span>Humidity (%): </span> <span class="city-result"><?= $block->getHumidity() ?></span></li>
                    <li><span>Wind Speed (meter/sec): </span> <span class="city-result"><?= $block->getWindSpeed() ?></span></li>
                    <li><span>Sunrise(UTC): </span> <span class="city-result"><?= $block->getSunrise() ?></span></li>
                    <li><span>Sunset(UTC): </span> <span class="city-result"><?= $block->getSunset() ?></span></li>
                </ul>
            </div>
        </div>
        </div>
    </form>

    <button class="search-btn" id="print-pdf">
        Print PDF
    </button>
</div>

<script>
    require(['jquery', 'jquery/ui'], function($) {
        jQuery(".search-btn").on('click', function() {
            document.getElementById('weather-form').submit();
        });

        $('#print-pdf').on('click', function () {
            window.location.href = 'weather/index/getpdf';
        })
    });

</script>
