<style>
    th, td {
        padding: 2px;
        font-size: 15px;
    }

    table, th, td {
        border: 1px dash;
        border-collapse: collapse;
    }
</style>
<table>
    <thead>
    <tr>
        <?php foreach ($block->getTableTitlesForPDF() as $title) : ?>
            <th>
                <?= $title ?>
            </th>
        <?php endforeach; ?>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($block->getDataForPDF() as $item) : ?>
        <tr>
            <td><?= $item->getId() ?></td>
            <td><?= $item->getCity() ?></td>
            <td><?= $item->getCountry() ?></td>
            <td><?= $item->getTemperature() ?></td>
            <td><?= $item->getFeelsLike() ?></td>
            <td><?= $item->getPressure() ?></td>
            <td><?= $item->getHumidity() ?></td>
            <td><?= $item->getWindSpeed() ?></td>
            <td><?= $item->getSunrise() ?></td>
            <td><?= $item->getSunset() ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
